name: 'Sonar'
description: 'Run analysis for pull requests'

inputs:
  sonar_token:
    description: 'Secret Sonar token'
    required: true

  artifactory_username:
    description: 'Secret Artifactory username'
    required: true

  artifactory_password:
    description: 'Secret Artifactory password'
    required: true

  sonar_url:
    description: 'Sonar url'
    required: true

  sonar_project_key:
    description: 'Sonar project key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Sonar: Get latest sonar-maven-plugin version"
      shell: bash
      env:
        ARTIFACTORY_USERNAME: ${{ inputs.artifactory_username }}
        ARTIFACTORY_PASSWORD: ${{ inputs.artifactory_password }}
      run: |
        URL=https://mvn.clever-shuttle.com/artifactory/libs-release/org/sonarsource/scanner/maven/sonar-maven-plugin/maven-metadata.xml
        LATEST_VERSION=$(curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD -s $URL | grep latest | sed "s/.*<latest>\([^<]*\)<\/latest>.*/\1/")
        
        if [ -z "$LATEST_VERSION" ]; then
          echo "Use default sonar-maven-plugin '3.9.1.2184'"
          echo "SONAR_MAVEN_PLUGIN_VERSION=3.9.1.2184" >> $GITHUB_ENV
        else
          echo "Use latest sonar-maven-plugin '$LATEST_VERSION'"
          echo "SONAR_MAVEN_PLUGIN_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        fi

    - name: "Sonar"
      shell: bash
      # https://docs.sonarqube.org/latest/analysis/analysis-parameters/
      env:
        SONAR_URL: ${{ inputs.sonar_url }}
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_PROJECT_KEY: ${{ inputs.sonar_project_key }}
        EVENT_NUMBER: ${{ github.event.number }}
        BRANCH_NAME: ${{ github.HEAD_REF }}
        PR_BASE: ${{ github.event.pull_request.base.ref }}
        REPOSITORY: ${{ github.repository }}
      # https://docs.sonarqube.org/latest/analysis/pull-request/
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:"$SONAR_MAVEN_PLUGIN_VERSION":sonar
        -Dsonar.host.url="$SONAR_URL"
        -Dsonar.login="$SONAR_TOKEN"
        -Dsonar.projectKey="$SONAR_PROJECT_KEY"
        -Dsonar.scm.provider=git
        -Dsonar.sourceEncoding=UTF-8
        -Dsonar.verbose=true
        -Dsonar.language=java
        -Dsonar.qualitygate.wait=true
        -Dsonar.qualitygate.timeout=300
        -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
        -Dsonar.dependencyCheck.htmlReportPath=target/site/dependency-check-report.html
        -Dsonar.pullrequest.provider=GitHub
        -Dsonar.pullrequest.key="$EVENT_NUMBER"
        -Dsonar.pullrequest.branch="$BRANCH_NAME"
        -Dsonar.pullrequest.base="$PR_BASE"
        -Dsonar.pullrequest.github.repository="$REPOSITORY"
