name: 'Generate nonprod changelog'
description: 'Generate nonprod changelog'

outputs:
  changelog:
    description: 'The generated changelog'
    value: ${{ steps.create-nonprod-changelog.outputs.changelog }}

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
    - name: 'Generate changelog'
      id: create-nonprod-changelog
      shell: bash
      run: |
        set -o nounset -o errexit
        output=$(git log --merges origin/master..origin/nonprod_test \
          | grep 'into nonprod' \
          | sed -rn 's/^\s*Merge remote-tracking branch '"'("'.*'")'"' into nonprod/\1/p' \
          | sort | uniq)
        echo "::set-output name=changelog::$output"
