name: 'Generate nonprod changelog'
description: 'Generate nonprod changelog'

outputs:
  changelog:
    description: 'The generated changelog'
    value: ${{ steps.create-nonprod-changelog.outputs.changelog }}

runs:
  using: 'composite'
  steps:
    - name: "Env variable: General"
      shell: bash
      env:
        REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: echo "REPO_BASE_URL=https://github.com/CleverShuttle/$REPOSITORY_NAME" >> $GITHUB_ENV

    - name: 'Generate changelog'
      shell: bash
      id: create-nonprod-changelog
      run: |
        set -o nounset -o errexit
        git restore .
        git fetch origin
        git checkout nonprod
        output=$(node ${{ github.action_path }}/generate-nonprod-changelog.js "$REPO_BASE_URL")
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=changelog::$output"

    - name: 'Outputs'
      shell: bash
      env:
        CHANGELOG: ${{ steps.create-nonprod-changelog.outputs.changelog }}
      run: |
        echo "Changelog: '$CHANGELOG'"
