name: 'Lint commit messages'
description: 'Lints pull request commits with commitlint'

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: "Lint commit messages"
      # https://github.com/wagoid/commitlint-github-action
      uses: wagoid/commitlint-github-action@v2.0.3
      with:
        failOnWarnings: true
        configFile: ${{ github.action_path }}/commitlint.config.js
