name: 'Lint commit messages'
description: 'Lints pull request commits with commitlint'

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3<
      with:
        fetch-depth: 0

    - name: "Copy config to workspace"
      shell: bash
      run: cp "${{ github.action_path }}/commitlint.config.js" .commitlint.config.js

    - name: "Lint commit messages"
      # https://github.com/wagoid/commitlint-github-action
      uses: wagoid/commitlint-github-action@v2.2.5
      with:
        failOnWarnings: true
        configFile: .commitlint.config.js

    - name: "Delete config from workspace"
      if: ${{ always() }}
      shell: bash
      run: rm .commitlint.config.js
