name: 'Sonar'
description: 'Run analysis for master'

inputs:
  sonar_token:
    description: 'Secret Sonar token'
    required: true

  artifactory_username:
    description: 'Secret Artifactory username'
    required: true

  artifactory_password:
    description: 'Secret Artifactory password'
    required: true

  sonar_url:
    description: 'Sonar url'
    required: true

  sonar_project_key:
    description: 'Sonar project key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: "Sonar: Get latest sonar-maven-plugin version"
      shell: bash
      run: |
        URL=https://mvn.clever-shuttle.com/artifactory/libs-release/org/sonarsource/scanner/maven/sonar-maven-plugin/maven-metadata.xml
        LATEST_VERSION=$(curl -u${{ inputs.artifactory_username }}:${{ inputs.artifactory_password }} -s $URL | grep latest | sed "s/.*<latest>\([^<]*\)<\/latest>.*/\1/")
        
        if [ -z "$LATEST_VERSION" ]; then
          echo "Use default sonar-maven-plugin '3.9.1.2184'"
          echo "SONAR_MAVEN_PLUGIN_VERSION=3.9.1.2184" >> $GITHUB_ENV
        else
          echo "Use latest sonar-maven-plugin '$LATEST_VERSION'"
          echo "SONAR_MAVEN_PLUGIN_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        fi

    - name: "Sonar"
      shell: bash
      # https://docs.sonarqube.org/latest/analysis/analysis-parameters/
      run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:${{ env.SONAR_MAVEN_PLUGIN_VERSION }}:sonar
        -Dsonar.host.url=${{ inputs.sonar_url }}
        -Dsonar.login=${{ inputs.sonar_token }}
        -Dsonar.projectKey=${{ inputs.sonar_project_key }}
        -Dsonar.scm.provider=git
        -Dsonar.sourceEncoding=UTF-8
        -Dsonar.verbose=true
        -Dsonar.language=java
        -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
        -Dsonar.dependencyCheck.htmlReportPath=target/site/dependency-check-report.html
        -Dsonar.branch.name=${GITHUB_REF:11}
