name: 'Sonar'
description: 'Run analysis for pull requests'

inputs:
  github_token:
    description: 'Secret GitHub token'
    required: true

  sonar_token:
    description: 'Secret Sonar token'
    required: true

  sonar_url:
    description: 'Sonar url'
    required: true

  sonar_project_key:
    description: 'Sonar project key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Setup sonarqube'
      # https://github.com/Warchant/setup-sonar-scanner
      uses: warchant/setup-sonar-scanner@v3

    - name: "Sonar"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      # https://github.com/SonarSource/sonar-scanner-cli/releases
      # https://docs.sonarqube.org/latest/analysis/analysis-parameters/
      # https://docs.sonarqube.org/latest/analysis/pull-request/
      run: sonar-scanner
        -Dsonar.host.url=${{ inputs.sonar_url }}
        -Dsonar.login=${{ inputs.sonar_token }}
        -Dsonar.projectKey=${{ inputs.sonar_project_key }}
        -Dsonar.scm.provider=git
        -Dsonar.sourceEncoding=UTF-8
        -Dsonar.verbose=true
        -Dsonar.language=java
        -Dsonar.sources=$GITHUB_WORKSPACE
        -Dsonar.qualitygate.wait=true
        -Dsonar.qualitygate.timeout=300
        -Dsonar.dependencyCheck.reportPath=target/dependency-check-report.xml
        -Dsonar.dependencyCheck.htmlReportPath=target/site/dependency-check-report.html
        -Dsonar.pullrequest.provider=GitHub
        -Dsonar.pullrequest.key=${{ github.event.number }}
        -Dsonar.pullrequest.branch=${{ github.HEAD_REF }}
        -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
        -Dsonar.pullrequest.github.repository=${{ github.repository }}

