name: 'Rebase nonprod onto default branch'
description: 'Rebase nonprod onto default branch'

runs:
  using: 'composite'
  steps:
    - name: "Get default branch"
      id: branch-name
      # https://github.com/tj-actions/branch-names
      uses: tj-actions/branch-names@v5

    - name: "Echo branches"
      shell: bash
      run: |
        echo "default_branch: ${{ steps.branch-name.outputs.default_branch }}"
        echo "base_ref_branch: ${{ steps.branch-name.outputs.base_ref_branch }}"
        echo "current_branch: ${{ steps.branch-name.outputs.current_branch }}"

    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.branch-name.outputs.base_ref_branch }}
        # The default of 1 only fetches the default branch. We also want nonprod, so we fetch all.
        fetch-depth: 0

    - name: "Setup git config"
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"

    - name: "Rebase nonprod onto default branch"
      shell: bash
      run: |
        if git switch nonprod 2>/dev/null; then
          echo "nonprod branch exists. Rebasing it onto ${{ steps.branch-name.outputs.base_ref_branch }}"
          git rebase origin/${{ steps.branch-name.outputs.base_ref_branch }}
        else
          echo "nonprod branch does not exist. Creating it from ${{ steps.branch-name.outputs.base_ref_branch }}"
          git checkout -b nonprod origin/${{ steps.branch-name.outputs.base_ref_branch }}
        fi

    - name: "Push changes"
      shell: bash
      run: |
        git push --force origin nonprod
