name: 'Merge to nonprod'
description: 'Merge to nonprod'

runs:
  using: 'composite'
  steps:
    - name: "Get default branch"
      id: branch-name
      # https://github.com/tj-actions/branch-names
      uses: tj-actions/branch-names@v5

    - name: "Echo branches"
      shell: bash
      run: |
        echo "default_branch: ${{ steps.branch-name.outputs.default_branch }}"
        echo "base_ref_branch: ${{ steps.branch-name.outputs.base_ref_branch }}"
        echo "current_branch: ${{ steps.branch-name.outputs.current_branch }}"

    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        ref: ${{ steps.branch-name.outputs.base_ref_branch }}
        # The default of 1 only fetches the default branch. We also want nonprod, so we fetch all.
        fetch-depth: 0

    - name: "Setup git config"
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"

    - name: "Prepare nonprod"
      shell: bash
      run: |
        set -o errexit -o nounset
        if git switch nonprod 2>/dev/null; then
          echo "nonprod branch exists. Merging ${{ steps.branch-name.outputs.base_ref_branch }}."
          git merge "${{ steps.branch-name.outputs.base_ref_branch }}"
        else
          echo "nonprod branch does not exist. Creating it from ${{ steps.branch-name.outputs.base_ref_branch }}"
          git checkout -b nonprod origin/${{ steps.branch-name.outputs.base_ref_branch }}
        fi

    - name: "Merge feature to nonprod"
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        set -o nounset -o errexit
        # no fast forward. every merged feature branch should be represented in the log with a merge commit to
        # generate the changelog later
        git merge --no-edit --no-ff "origin/$BRANCH_NAME"

    - name: "Push changes"
      shell: bash
      run: |
        git push origin nonprod
