name: 'Merge to nonProd'
description: 'Merge to nonProd'

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        ref: master
        # The default of 1 only fetches the default branch. We also want nonProd, so we fetch all.
        fetch-depth: 0

    - name: "Setup git config"
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"

    - name: "Prepare nonProd"
      shell: bash
      run: |
        set -o errexit -o nounset
        if git switch nonprod 2>/dev/null; then
          branchName="${{ github.head_ref }}"
          # https://stackoverflow.com/a/29613573/5390250
          escapedBranchName=$(sed "s/[^^]/[&]/g; s/\^/\\^/g" <<< "$branchName")
          echo "nonProd branch exists. Dropping old feature commit '$branchName' if it exists"
          GIT_SEQUENCE_EDITOR="sed -i -e \"s/pick\(.*$escapedBranchName\)$/drop\1/g\"" git rebase -i master
        else
          echo "nonProd branch does not exist. Creating it from master"
          git checkout -b nonprod origin/master
        fi

    - name: "Merge feature to nonProd"
      shell: bash
      run: |
        set -o nounset -o errexit
        git merge --squash "origin/${{ github.head_ref }}"
        git commit -m "${{ github.head_ref }}"

    - name: "Push changes"
      shell: bash
      run: |
        git push --force origin nonprod
