name: 'Merge to nonprod'
description: 'Merge to nonprod'

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        # https://stackoverflow.com/a/71158878
        ref: ${{ github.head_ref || github.ref_name }}
        # The default of 1 only fetches the default branch. We also want nonprod, so we fetch all.
        fetch-depth: 0

    - name: "Setup git config"
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"

    - name: "Prepare nonprod"
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        set -o errexit -o nounset
        if git switch nonprod 2>/dev/null; then
          branchName="$BRANCH_NAME"
          # https://stackoverflow.com/a/29613573/5390250
          escapedBranchName=$(sed "s/[^^]/[&]/g; s/\^/\\^/g" <<< "$branchName")
          echo "nonprod branch exists. Dropping old feature commit '$branchName' if it exists"
          GIT_SEQUENCE_EDITOR="sed -i -e \"s/pick\(.*$escapedBranchName\)$/drop\1/g\"" git rebase -i master
        else
          echo "nonprod branch does not exist. Creating it from master"
          git checkout -b nonprod origin/master
        fi

    - name: "Merge feature to nonprod"
      shell: bash
      env:
        BRANCH_NAME: ${{ github.head_ref }}
      run: |
        set -o nounset -o errexit
        git merge --squash "origin/$BRANCH_NAME"
        git commit -m "$BRANCH_NAME"

    - name: "Push changes"
      shell: bash
      run: |
        git push --force origin nonprod
