name: 'Notification: Append Changelog'
description: 'Reads changelog from release and appends it to Slack message'

inputs:
  slack_bot_token:
    description: 'Slack bot token'
    required: true

  slack_channel:
    description: 'Slack channel'
    required: true

  slack_thread_ts:
    description: 'Slack thread TS'
    required: true

  release:
    description: 'Release'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Changelog: Setup Node'
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: 'Changelog: Read Release Body'
      # https://github.com/cardinalby/git-get-release-action
      uses: cardinalby/git-get-release-action@1.2.2
      id: release-info
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        tag: ${{ inputs.release }}

    - name: 'Changelog: Generate Jira links'
      id: changelog_with_links
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        CHANGELOG: ${{ steps.release-info.outputs.body }}
      run: |
        if [ -z "${{ env.CHANGELOG }}" ]; then
          output=""
          echo "::set-output name=text::$output"
        else
          output=$(node generate-jira-links.js)
          # fix multiline output encoding
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=text::$output"
        fi

    - name: 'Changelog: Format changelog for Slack'
      uses: lovetoknow/slackify-markdown-action@v1.0.0
      id: changelog_with_markdown_links
      with:
        text: ${{ steps.changelog_with_links.outputs.text }}

    - name: 'Notification: Append Changelog'
      uses: archive/github-actions-slack@master
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ inputs.slack_bot_token }}
        slack-channel: ${{ inputs.slack_channel }}
        slack-optional-thread_ts: ${{ inputs.slack_thread_ts }}
        slack-text: ${{ steps.changelog_with_markdown_links.outputs.text }}
