name: 'Notification: Template'
description: 'TBD'

inputs:
  text:
    default: 'Deploying __{{subject}}__ to ___{{env}}___'
    description: 'Text message to render'
    required: false

  subject:
    description: 'TBD'
    required: false

  env:
    description: 'Target environment'
    required: false

outputs:
  text:
    description: 'TBD'
    value: ${{ steps.template-output.outputs.text }}

runs:
  using: 'composite'
  steps:
    - name: '✏️ Template: Set message'
      shell: bash
      run: |
        echo "${{ inputs.text }}" >> slack_text.tmp

    - name: '✏️ Template: Render message'
      id: template_start_notification
      # https://github.com/marketplace/actions/template-render-action
      uses: recih/template-render-action@v1
      with:
        engine: mustache
        template-file: slack_text.tmp
        vars: |
          { 
            "subject": "${{ inputs.subject }}", 
            "env": "${{ inputs.env }}" 
          }

    - name: '✏️ Template: Echo render output'
      shell: bash
      run: echo "${{ steps.template_start_notification.outputs.content }}"

    - name: '✏️ Template: Set output'
      id: template-output
      shell: bash
      run: |
        echo "${{ steps.template_start_notification.outputs.content }}" | sed 's/___/`/g' >> slack_text.tmp
        cat slack_text.tmp | sed 's/__/*/g' >> slack_text.tmp
        TEXT=`cat slack_text.tmp`
        echo "$TEXT"
        echo "::set-output name=text::$TEXT"
