name: 'Generate changelog'
description: 'Generate a changelog with conventional commits'

outputs:
  clean_changelog:
    description: 'The generated changelog for the new version without the version name in it (Better for Github releases)'
    value: ${{ steps.changelog.outputs.clean_changelog }}

  skipped:
    description: 'Boolean specifying if this step have been skipped'
    value: ${{ steps.changelog.outputs.skipped }}

  version:
    description: 'The new version'
    value: ${{ steps.changelog.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: "Checkout repository"
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 'Setup: Install dependencies'
      shell: bash
      run: npm i conventional-changelog-conventionalcommits

    # https://github.com/TriPSs/conventional-changelog-action
    - name: "Generate changelog"
      id: changelog
      uses: TriPSs/conventional-changelog-action@v3.11.0
      with:
        github-token: ${{ github.token }}
        skip-on-empty: true
        output-file: false
        skip-version-file: true
        skip-commit: true
        config-file-path: ${{ github.action_path }}/changelog.config.js

    - name: "Debug: Outputs"
      shell: bash
      run: |
        echo "Clean changelog: '${{ steps.changelog.outputs.clean_changelog }}'"
        echo "Version: '${{ steps.changelog.outputs.version }}'"
        echo "Skipped: '${{ steps.changelog.outputs.skipped }}'"
