name: 'Composite-Actions: Lint commit messages'

on:
  pull_request:

jobs:
  lint-commits:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Lint commit messages"
        # https://github.com/wagoid/commitlint-github-action
        uses: wagoid/commitlint-github-action@v2.0.3
        with:
          failOnWarnings: true
          configFile: 'actions/lint-commits/commitlint.config.js'
