name: 'Test'
on:
  workflow_dispatch: { }

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start
        run: echo "Starting"

      - name: 'Notification: Template'
        id: template-messages
        uses: ./actions/template-messages
        with:
          text: 'Deploying __{{subject}}__ to ___{{env}}___'
          subject: 'Test-Subject'
          env: 'Prod-XXX'

      - name: Print outputs
        run: |
          echo "Slack text: ${{ steps.notification-template.outputs.text }}"

#    steps:
#      - name: '✏️ Template: Set message'
#        shell: bash
#        run: |
#          echo 'SLACK_TEXT=Deploying {{subject}} to `{{env}}`' >> slack_text.tmp
#
#      - name: '✏️ Template: Replace backticks'
#        shell: bash
#        run: |
#          cat slack_text.tmp | sed 's/`/___/g' >> slack_text.tmp
#          SLACK_TEXT=`cat slack_text.tmp`
#          echo "SLACK_TEXT=$SLACK_TEXT" >> $GITHUB_ENV
#
#      - name: '✏️ Template: Render message'
#        id: template_start_notification
#        # https://github.com/marketplace/actions/template-render-action
#        uses: recih/template-render-action@v1
#        with:
#          engine: mustache
#          template: "${{ env.SLACK_TEXT }}"
#          vars: |
#            { "subject": "XYZ", "env": "Prod" }
#
#      - name: '✏️ Template: Echo render output'
#        shell: bash
#        run: echo "${{ steps.template_start_notification.outputs.content }}"
#
#      - name: '✏️ Template: Set output'
#        shell: bash
#        run: |
#          echo "${{ steps.template_start_notification.outputs.content }}" | sed 's/___/`/g' >> slack_text.tmp
#          SLACK_TEXT=`cat slack_text.tmp`
#          echo "$SLACK_TEXT"
#          echo "SLACK_TEXT=$SLACK_TEXT" >> $GITHUB_ENV